# 构建 VitePress 站点并将其部署到 GitHub Pages 的示例工作流程
#
name: Deploy VitePress site to Pages

on:
  # 在针对 `main` 分支的推送上运行。如果你
  # 使用 `master` 分支作为默认分支，请将其更改为 `master`
  push:
    branches: [master]

  # 允许你从 Actions 选项卡手动运行此工作流程
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许同时进行一次部署，跳过正在运行和最新队列之间的运行队列
# 但是，不要取消正在进行的运行，因为我们希望允许这些生产部署完成
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # 构建工作
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 如果未启用 lastUpdated，则不需要
      - name: Setup pnpm
        uses: pnpm/action-setup@v3 # 使用pnpm官方Action
        with:
          version: 10.6.5 # 指定pnpm版本
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.2 # 指定与本地相同的Node.js版本
          cache: pnpm # 使用pnpm缓存
      - name: Setup Pages
        uses: actions/configure-pages@v4 # 在工作流程自动配置GithubPages
      - name: Clean pnpm cache
        run: pnpm store prune
      - name: Install dependencies
        run: pnpm install
      - name: Build with VitePress
        run: pnpm run docs:build 
        # 启动项目
      - name: Create .nojekyll file
        run: touch .vitepress/dist/.nojekyll # 创建.nojekyll文件防止GitHub Pages使用Jekyll处理
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .vitepress/dist

  # 部署工作
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build # 在build后面完成
    runs-on: ubuntu-latest # 使用最新的Ubuntu运行器
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment # 部署步骤的ID
        uses: actions/deploy-pages@v4 # 使用GitHub Pages部署操作
